### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Hasanmog** [like413/OPT-RSVG#2]
Hello, 

Are you going to release the dataset anytime soon ? 

cc : @aghand0ur

**Comment by like413** [comment]
> Hello,
> 
> Are you going to release the dataset anytime soon ?
> 
> cc : @aghand0ur

We are pleased to announce the release of our dataset. You are welcome to download it and explore.

**Comment by Hasanmog** [comment]
Great Work! 
Thank you.

**Comment by Hasanmog** [comment]
Hello again @like413   , 
did you release the English version of the dataset ? 
I was exploring the one released, and from what I saw the descriptions are in just Chinese. 
if so , can you please share the English Annotation version ?

**Comment by Hasanmog** [comment]
The English annotation file has been uploaded to the google drive link.
