### ISSUE TITLE
confused about the result on DIOR-RSVG

### ISSUE THREAD

**Issue by Dawnlight-Sion** [like413/OPT-RSVG#3]
Great work! Hope to publish soon.
But when I'm running the code of MGVLF, I can only get 73.91% Pr@0.5 on DIOR-RSVG, is your code run on DIOR-RSVG of the config below?
trainset: 26991 validationset: 3829 testset: 7500

Look forward to your reply.

**Comment by like413** [comment]
Thanks! MGVLF has previously updated the division of the DIOR-RSVG, but unfortunately the code has been deleted.

**Comment by like413** [comment]
Thanks! MGVLF has previously updated the division of the DIOR-RSVG, but unfortunately the code has been deleted.
Feel free to use our OPT-RSVG to validate your methods

**Comment by Dawnlight-Sion** [comment]
Good choice, I may give it a try, thanks for your suggestions.
