### ISSUE TITLE
Dimension mismatch error in PA.py

### ISSUE THREAD

**Issue by gai-zi** [like413/OPT-RSVG#4]
Hi,

I encountered a dimension mismatch error in PA.py. The error occurred because the language_features passed into the function is a 2D tensor, but your code applies a permute operation on it as if it were 3D.

Here are the steps I took:

I adjusted the dimensions to ensure proper alignment.
After fixing the dimensions, I ran the model and got the following output, but it seems the model hasn't learned the features properly.
Can you help me understand why the model might not be learning the features, even after fixing the dimension mismatch?

![image](https://github.com/user-attachments/assets/6e566832-831f-4c6f-86c4-060aa883a1e5)

![image](https://github.com/user-attachments/assets/d35da951-bf70-4ac0-b84e-9769b06e9af4)

Thank you!

**Comment by AICyberTeam** [comment]
Hello, I encountered the same issue during my reproduction process. I would like to ask how you eventually resolved it.

**Comment by Yu-Ruiqing** [comment]
我也遇到了同样的问题，请问您是怎么解决的

**Comment by Yu-Ruiqing** [comment]
I'm having the same problem, may I ask how you solved it?

**Comment by Yu-Ruiqing** [comment]
> 你好
> 
> 我在 PA.py 中遇到了尺寸不匹配错误。发生此错误的原因是传入函数的language_features是 2D 张量，但您的代码对其应用 permute 运算，就像它是 3D 一样。
> 
> 以下是我采取的步骤：
> 
> 我调整了尺寸以确保正确对齐。修复尺寸后，我运行了模型并获得了以下输出，但模型似乎没有正确学习这些功能。您能否帮助我了解为什么即使在修复尺寸不匹配之后，模型也可能没有学习这些特征？
> 
> ![image](https://github.com/user-attachments/assets/6e566832-831f-4c6f-86c4-060aa883a1e5)
> 
> ![image](https://github.com/user-attachments/assets/d35da951-bf70-4ac0-b84e-9769b06e9af4)
> 
> 谢谢！

我遇到了同样的问题，请问您是怎么解决的？

**Comment by Yu-Ruiqing** [comment]
> Hi,
> 
> I encountered a dimension mismatch error in PA.py. The error occurred because the language_features passed into the function is a 2D tensor, but your code applies a permute operation on it as if it were 3D.
> 
> Here are the steps I took:
> 
> I adjusted the dimensions to ensure proper alignment. After fixing the dimensions, I ran the model and got the following output, but it seems the model hasn't learned the features properly. Can you help me understand why the model might not be learning the features, even after fixing the dimension mismatch?
> 
> ![image](https://github.com/user-attachments/assets/6e566832-831f-4c6f-86c4-060aa883a1e5)
> 
> ![image](https://github.com/user-attachments/assets/d35da951-bf70-4ac0-b84e-9769b06e9af4)
> 
> Thank you!

I have the same problem, how did you solve it?

**Comment by Kehope** [comment]
> > Hi,
> > I encountered a dimension mismatch error in PA.py. The error occurred because the language_features passed into the function is a 2D tensor, but your code applies a permute operation on it as if it were 3D.
> > Here are the steps I took:
> > I adjusted the dimensions to ensure proper alignment. After fixing the dimensions, I ran the model and got the following output, but it seems the model hasn't learned the features properly. Can you help me understand why the model might not be learning the features, even after fixing the dimension mismatch?
> > ![image](https://github.com/user-attachments/assets/6e566832-831f-4c6f-86c4-060aa883a1e5)
> > ![image](https://github.com/user-attachments/assets/d35da951-bf70-4ac0-b84e-9769b06e9af4)
> > Thank you!
> 
> I have the same problem, how did you solve it?

Have you solved this problem?
